variables:
  RUST_BACKTRACE: 1

image: rust:latest

stages:
  - build
  - test
  - deploy

cache: &cache_template
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target
    - .cargo
  policy: pull-push

.cache_pull_template: &cache_pull_template
  cache:
    <<: *cache_template
    policy: pull

build::default:
  stage: build
  script:
    - cargo build
  cache:
    <<: *cache_template

build::wasm:
  stage: build
  script: ./build_wasm.sh
  cache:
    <<: *cache_template
  artifacts:
    paths:
      - public

test:clippy:
  <<: *cache_pull_template
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings

test::rustfmt:
  <<: *cache_pull_template
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

pages:
  <<: *cache_pull_template
  stage: deploy
  script: pwd
  needs:
    - build::wasm
  only:
    refs:
      - master
  artifacts:
    paths:
      - public